authapp/urls.py
# from authapp.views import LoginView, RegisterView, EditView, LogoutView
from authapp import views
from django.urls import path
from authapp.apps import AuthappConfig
from django.views.generic.base import RedirectView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('edit/', views.EditView.as_view(), name='edit'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

braniaclms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url="home/")),
    path('login/', RedirectView.as_view(url="/authapp/login")),
    path('home/', include('mainapp.urls', namespace='home')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from mainapp import views
from django.urls import path
from mainapp.apps import MainappConfig
from django.views.generic.base import RedirectView
from django.views.decorators.cache import cache_page

app_name = MainappConfig.name

urlpatterns = [
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('', views.IndexView.as_view(), name='home'),
    path('yandex/', RedirectView.as_view(url='https://yandex.ru/search/', query_string=True), name='yandex'),

    # News
    path('news/', views.NewsView.as_view(), name='news'),
    path('news/add/', views.NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    path('news/<int:pk>/detail/', views.NewsDetailView.as_view(), name='news_detail'),

    #Courses
    path('courses/', cache_page(600)(views.CoursesListView.as_view()), name="courses"),
    path('courses/<int:pk>/detail/', views.CourseDetailView.as_view(), name="courses_detail"),
    path('courses/course_feedback/', views.CourseFeedbackFormView.as_view(), name="course_feedback"),

    #Logs
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

mainapp/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')
    deleted = models.BooleanField(default=False, verbose_name='Удалено')

    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()


class News(BaseModel):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    preambule = models.CharField(max_length=2255, verbose_name='Превью')
    body = models.TextField(verbose_name='Новость')
    body_as_markdown = models.BooleanField(default=False, verbose_name='Маркдаун')

    def __str__(self):
        return f'{self.title} {self.created}'

    class Meta:
        ordering = ['-created', 'title']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Courses(BaseModel):
    name = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    description_as_markdown = models.BooleanField(default=True, verbose_name='Маркдаун')
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    cover = models.CharField(max_length=124, verbose_name='Изображение', default='No image')

    def __str__(self):
        return f'{self.name} {self.created}'

    class Meta:
        ordering = ['-cost', 'name']
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'


class Lesson(BaseModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, blank=True, null=True)
    num = models.PositiveIntegerField(verbose_name='Номер урока')
    title = models.CharField(max_length=50, verbose_name='Название урока')
    description = models.CharField(max_length=255, verbose_name='Описание урока')
    description_as_markdown = models.BooleanField(default=False, verbose_name='Маркдаун')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['course', 'num']
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'


class CourseTeachers(models.Model):
    name_first = models.CharField(max_length=100, verbose_name='Имя')
    name_second = models.CharField(max_length=100, verbose_name='Фамилия')
    day_birth = models.DateField(verbose_name='День рождения')
    course = models.ManyToManyField(Courses)
    deleted = models.BooleanField(default=False, verbose_name='Удалено')

    def __str__(self):
        return f'{self.name_first} {self.name_second}'

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = 'Препоаватель'
        verbose_name_plural = 'Преподаватели'


class CourseFeedback(BaseModel):
    RAITING_FIVE = 5
    RAITING_FOUR = 4
    RAITING_THREE = 3
    RAITING_TWO = 2
    RAITING_ONE = 1

    RATINGS = (
        (RAITING_FIVE, '⭐⭐⭐⭐⭐'),
        (RAITING_FOUR, '⭐⭐⭐⭐'),
        (RAITING_THREE, '⭐⭐⭐'),
        (RAITING_TWO, '⭐⭐'),
        (RAITING_ONE, '⭐'),
    )

    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    feedback = models.TextField(verbose_name='Отзыв', default='Без отзыва')
    rating = models.PositiveSmallIntegerField(choices=RATINGS, default=RAITING_FIVE, verbose_name='Рейтинг')

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'

    def __str__(self):
        return f'Отзыв от {self.user} на курс {self.course}'

mainapp/forms.py
from django import forms
from mainapp.models import CourseFeedback


class CourseFeedbackForm(forms.ModelForm):
    class Meta:
        model = CourseFeedback
        fields = ['course', 'user', 'rating', 'feedback']
        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            # 'rating': forms.HiddenInput()
        }

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk

mainapp/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, FileResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.core.cache import cache
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from mainapp import tasks
from django.http.response import HttpResponseRedirect

from mainapp.forms import CourseFeedbackForm
from mainapp.models import News, Courses, Lesson, CourseTeachers, CourseFeedback

import logging

logger = logging.getLogger(__name__)


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'adress': 'территория Петропавловская крепость, 3Ж'
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'adress': 'территория Кремль, 11, Казань, Республика Татарстан, Россия'
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'adress': 'Красная площадь, 7, Москва, Россия'
            }
        ]
        return context_data

    def post(self, *args, **kwargs):
        message_body = self.request.POST.get('message_body')
        message_from = self.request.user.pk if self.request.user.is_authenticated else None
        tasks.send_feedback_mail.delay(message_body, message_from)
        return HttpResponseRedirect(reverse_lazy("mainapp:contacts"))


class CoursesView(TemplateView):
    template_name = 'mainapp/courses_list.html'


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


# class NewsView(TemplateView):
#     template_name = 'mainapp/news.html'
#
#     def get_context_data(self, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['object_list'] = News.objects.filter(deleted=False)
#         return context_data
#
#
# class NewsWithPagination(NewsView):
#
#     def get_context_data(self, page, **kwargs):
#         context = super().get_context_data(page=page, **kwargs)
#         context["page_num"] = page
#         return context

class NewsView(ListView):
    model = News
    paginate_by = 5

    def get_queryset(self):
        dateFrom = self.request.GET.get('dateFrom')
        dateTo = self.request.GET.get('dateTo')
        if dateFrom and dateTo:
            return super().get_queryset().filter(deleted=False).filter(created__range=(dateFrom, dateTo))
        elif dateFrom and dateTo is None:
            return super().get_queryset().filter(deleted=False).filter(created__startswith=dateFrom)
        else:
            return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News

    def get_object(self, queryset=None):
        return get_object_or_404(News, pk=self.kwargs.get('pk'), deleted=False)


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.add_news',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.change_news',)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.delete_news',)


class CourseDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['course_object'] = get_object_or_404(Courses, pk=self.kwargs.get('pk'))
        context_data['lessons'] = Lesson.objects.filter(course=context_data['course_object'])
        context_data['teachers'] = CourseTeachers.objects.filter(course=context_data['course_object'])
        feedback_list_key = f"course_feedback{context_data['course_object'].pk}"
        print(feedback_list_key)
        cached_feedback_list = cache.get(feedback_list_key)
        if cached_feedback_list is None:
            context_data['feedback_list'] = CourseFeedback.objects.filter(course=context_data['course_object'])
            cache.set(feedback_list_key, context_data['feedback_list'], timeout=600)
        else:
            context_data['feedback_list'] = cached_feedback_list
            print(context_data)
        if not self.request.user.is_anonymous:
            if not CourseFeedback.objects.filter(
                    course=context_data["course_object"],
                    user=self.request.user).count():
                context_data['feedback_form'] = CourseFeedbackForm(
                    course=context_data['course_object'],
                    user=self.request.user
                )
        return context_data


class CoursesListView(TemplateView):
    template_name = "mainapp/courses_list.html"

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context["objects"] = Courses.objects.all()
        return context


class CourseFeedbackFormView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedbackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_card = render_to_string('mainapp/includes/feedback_card.html', context={'item': self.object})
        return JsonResponse({'card': rendered_card})


class LogView(TemplateView):
    template_name = "mainapp/log_view.html"

    def get_context_data(self, **kwargs):
        """Переписал как и требовалось в 2b(**).
        Вывод только последнего кол-ва заданных строк указанных в lines_count"""
        context = super(LogView, self).get_context_data(**kwargs)
        log_slice = []
        lines_count = 10
        last_line = sum(1 for line in open(settings.LOG_FILE))
        with open(settings.LOG_FILE, "r") as log_file:
            for i, line in enumerate(log_file):
                if i < (last_line - lines_count):
                    continue
                log_slice.insert(0, f'{i} {line}')
            context["log"] = "".join(log_slice)
        return context


class LogDownloadView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))

mainapp/templates/mainapp/includes/feedback_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load i18n %}

{% with request.resolver_match.url_name as url_name %}


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link {% if url_name == 'news' %} active {% endif %}"
                   href="{% url 'mainapp:news' %}">{% translate "News" %}</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link {% if url_name == 'courses' %} active {% endif %}"
                   href="{% url 'mainapp:courses' %}">{% translate "Courses" %}</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {% translate "Profile" %}
                </a>
                <div class="dropdown-menu" aria-labelledby="ddProfile">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'authapp:edit' %}">{% translate "Edit profile" %}</a>
                        <a class="dropdown-item" href="#">{% translate "My courses" %}</a>
                        <div class="dropdown-divider"></div>
                    {% endif %}
                    {% if user.is_staff %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate "Moderation" %}</a>
                    {% endif %}
                    {% if user.is_superuser %}
                        <a class="dropdown-item"
                           href="{% url 'admin:index' %}">{% translate "Administrative section" %}</a>
                        <a class="dropdown-item" href="{% url 'mainapp:log_view' %}"
                           target="_blank">{% translate "Logging" %}</a>
                        <div class="dropdown-divider"></div>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'authapp:logout' %}">{% translate "Logout" %}</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'authapp:login' %}">{% translate "Login" %}</a>
                    {% endif %}
                </div>
            </li>
            <li class="nav-item {% if url_name == 'contacts' %} active {% endif %}">
                <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate "Contacts" %}</a>
            </li>
            <li class="nav-link active">
                {{ user.username }}
            </li>
        </ul>
        {#    <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>#}
        <div class="row justify-content-end m-0">
            <div class="col p-0 border-right">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="language" type="hidden" value="ru">
                    <button type="submit" class="btn btn-link">🇷🇺</button>
                </form>
            </div>
            <div class="col p-0 border-left">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="language" type="hidden" value="en">
                    <button type="submit" class="btn btn-link">🇬🇧</button>
                </form>
            </div>
        </div>

    </div>

{% endwith %}