authapp/urls.py
# from authapp.views import LoginView, RegisterView, EditView, LogoutView
from authapp import views
from django.urls import path
from authapp.apps import AuthappConfig
from django.views.generic.base import RedirectView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('edit/', views.EditView.as_view(), name='edit'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

braniaclms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url="home/")),
    path('login/', RedirectView.as_view(url="/authapp/login")),
    path('home/', include('mainapp.urls', namespace='home')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {
    'blank': True,
    'null': True
}


class User(AbstractUser):
    email = models.EmailField(verbose_name='Email', unique=True)
    age = models.PositiveSmallIntegerField(verbose_name='Возраст', **NULLABLE)
    avatar = models.ImageField(upload_to='users', verbose_name='Аватар', **NULLABLE)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        else:
            return age


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        else:
            return age

authapp/views.py
import os
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.views.generic import TemplateView, CreateView, UpdateView

from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from authapp.models import User


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }

    def form_valid(self, form):
        ret = super().form_valid(form)

        message = ("Login success!<br>Hi, %(username)s") % {
            "username": self.request.user.get_full_name()
            if self.request.user.get_full_name()
            else self.request.user.get_username()
        }
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        messages.add_message(self.request, messages.WARNING, 'Неправильно имя пользователя или пароль!')
        return self.render_to_response(self.get_context_data(form=form))


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('authapp:login')


# class RegisterView(TemplateView):
#     template_name = 'authapp/register.html'
#     extra_context = {
#         'title': 'Регистрация пользователя'
#     }
#
#     def post(self, request, *args, **kwargs):
#         try:
#             if all(
#                     (
#                             request.POST.get('username'),
#                             request.POST.get('password1'),
#                             request.POST.get('password2'),
#                             request.POST.get('first_name'),
#                             request.POST.get('last_name'),
#                             request.POST.get('email'),
#                             request.POST.get('password1') == request.POST.get('password2'),
#                     )
#             ):
#                 new_user = User.objects.create(
#                     username=request.POST.get('username'),
#                     first_name=request.POST.get('first_name'),
#                     last_name=request.POST.get('last_name'),
#                     email=request.POST.get('email'),
#                     age=request.POST.get('age') if request.POST.get('age') else 0,
#                     avatar=request.FILES.get('avatar')
#                 )
#                 new_user.set_password(request.POST.get('password1'))
#                 new_user.save()
#                 messages.add_message(request, messages.INFO, 'Реистрация успешна')
#                 return HttpResponseRedirect(reverse('authapp:login'))
#             else:
#                 messages.add_message(request, messages.WARNING, 'Что-то не получилось')
#                 return HttpResponseRedirect(reverse('authapp:register'))
#         except Exception as ex:
#             messages.add_message(request, messages.WARNING, f'Что-то не получилось {ex}')
#             return HttpResponseRedirect(reverse('authapp:register'))


# class EditView(CreateView):
#     model = User
#     form_class = CustomUserCreationForm
#     success_url = reverse_lazy('authapp:login')


class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'authapp/edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('authapp:edit', args=[self.request.user.pk])


# class EditView(TemplateView):
#     template_name = 'authapp/edit.html'
#     extra_context = {
#         'title': 'Изменение пользователя'
#     }
#
#     def post(self, request, *args, **kwargs):
#         try:
#             if request.POST.get("username"):
#                 request.user.username = request.POST.get("username")
#             if request.POST.get("first_name"):
#                 request.user.first_name = request.POST.get("first_name")
#             if request.POST.get("last_name"):
#                 request.user.last_name = request.POST.get("last_name")
#             if request.POST.get("age"):
#                 request.user.age = request.POST.get("age")
#             if request.POST.get("email"):
#                 request.user.email = request.POST.get("email")
#             if request.FILES.get("avatar"):
#                 if request.user.avatar and os.path.exists(request.user.avatar.path):
#                     os.remove(request.user.avatar.path)
#                 request.user.avatar = request.FILES.get("avatar")
#             request.user.save()
#             messages.add_message(request, messages.INFO, ("Saved!"))
#         except Exception as exp:
#             messages.add_message(
#                 request,
#                 messages.WARNING,
#                 mark_safe(f"Something goes worng:<br>{exp}"),
#             )
#         return HttpResponseRedirect(reverse("authapp:edit"))


class CustomLogoutView(LogoutView):
    template_name = 'mainapp/index.html'

authapp/templates/authapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>

{% include 'authapp/includes/messages.html' %}

<div class="row justify-content-around align-items-center" style="height: auto; margin: 0px">
    <div class="text-center">
        <p>
            <a href="{% url 'mainapp:home' %}"><img src="../../..{% static 'img/logo.png' %}" alt=""></a>
        </p>
        <h3>{{ title }}</h3>
        {% block content %}
        {% endblock %}
        <h4>Вход через социальные сети</h4>
        <p>
        <div class="btn-group btn-block" role="group">
            <a class="btn btn-primary" href="{% url 'social:begin' 'vk-oauth2' %}" role="button"><i class="fab fa-vk"></i></a>
            <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i class="fab fa-github"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
        </div>
        </p>
    </div>
</div>


<!-- Footer -->

<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="{% url 'mainapp:home' %}">Домашняя</a></li>
                <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
                {% else %}
                    <li><a href="{% url 'authapp:login' %}">Войти</a></li>
                {% endif %}
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Полезное</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">Положения &amp; Условия</a></li>
                <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                <li><a href="#">Документация по API</a></li>
                <li><a href="{% url 'mainapp:docsite' %}">Документация по сайту</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Мы в социальных сетях</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>Наше приложение</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; GeekBrains 2021</small></p>
        </div>
    </div>
</div>

<!-- /Footer -->


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static '/js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static '/js/fontawesome.all.min.js' %}"></script>

{% block js %}
{% endblock %}

</body>

</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row justify-content-center my-2">
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-5 col-lg-4">
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" alt="" width="100%">
                {% else %}
                    <img src="{{ MEDIA_URL }}avatar.svg" alt="" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type=" submit" class="btn btn-primary btn-block">
            Сохранить
        </button>
    </form>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000}); $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <p>
            <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя или email"
                   required="" autofocus="">
        </p>
        <p>
            <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль"
                   required="">
        </p>
        <p>
            <button type="submit" class="btn btn-primary btn-block">Войти</button>
        </p>
    </form>
    <div class="row justify-content-between">
        <div class="col"><a href="{% url 'authapp:register' %}"><small>Регистрация</small></a></div>
        <div class="col"><a href="#"><small>Забыли пароль?</small></a></div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000}); $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="div_id_username" class="form-group">
            <label for="id_username" class=" requiredField">
                Username
                <span class="asteriskField">*</span> </label>
            <div class="">
                <input type="text" name="username" maxlength="150" class="textinput textInput form-control" required="" id="id_username">
                <small id="hint_id_username" class="form-text text-muted">
                    Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                </small>
            </div>
        </div>
        <div id="div_id_password1" class="form-group">
            <label for="id_password1" class=" requiredField">
                Password
                <span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password1">
                <small id="hint_id_password1" class="form-text text-muted">
                    <ul>
                        <li>Your password can’t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ul>
                </small>
            </div>
        </div>
        <div id="div_id_password2" class="form-group">
            <label for="id_password2" class=" requiredField">
                Password confirmation
                <span class="asteriskField">*</span>
            </label>
            <div class=""><input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password2">
                <small id="hint_id_password2" class="form-text text-muted">
                    Enter the same password as before, for verification.
                </small>
            </div>
        </div>
        <div id="div_id_first_name" class="form-group">
            <label for="id_first_name" class="">
                First name
            </label>
            <div class="">
                <input type="text" name="first_name" maxlength="150" class="textinput textInput form-control" id="id_first_name">
            </div>
        </div>
        <div id="div_id_last_name" class="form-group">
            <label for="id_last_name" class="">
                Last name
            </label>
            <div class="">
                <input type="text" name="last_name" maxlength="150" class="textinput textInput form-control" id="id_last_name">
            </div>
        </div>
        <div id="div_id_age" class="form-group">
            <label for="id_age" class="">
                Age
            </label>
            <div class="">
                <input type="number" name="age" min="0" class="numberinput form-control" id="id_age">
            </div>
        </div>
        <div id="div_id_email" class="form-group">
            <label for="id_email" class=" requiredField">
                Email address
                <span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="text" name="email" maxlength="256" class="textinput textInput form-control" required="" id="id_email">
            </div>
        </div>
        <div id="div_id_avatar" class="form-group">
            <label for="id_avatar" class="">
                Avatar
            </label>
            <div class="">
                <input type="file" name="avatar" accept="image/*" class="clearablefileinput form-control-file" id="id_avatar">
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
    </form>
    <p>
    <div class="row justify-content-between">
        <div class="col"><a href="{% url 'authapp:login' %}"><small>Войти</small></a></div>
    </div>
    </p>


{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000}); $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
    </form>
    <p>
    <div class="row justify-content-between">
        <div class="col"><a href="{% url 'authapp:login' %}"><small>Войти</small></a></div>
    </div>
    </p>


{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000}); $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}